export const mockKpis = {
  callsYesterday: 42,
  callsThisWeek: 187,
  callsThisMonth: 634,
  avgDurationSeconds: 134,
  inboundCount: 512,
  outboundCount: 122,
  complaintsCount: 8,
  followUpRequired: 23,
  salesOpportunities: 14,
};

export const mockCallVolume = [
  { date: "May 26", calls: 38 },
  { date: "May 27", calls: 51 },
  { date: "May 28", calls: 44 },
  { date: "May 29", calls: 29 },
  { date: "May 30", calls: 47 },
  { date: "May 31", calls: 55 },
  { date: "Jun 1", calls: 42 },
];

export const mockCategories = [
  { category: "Scheduling", count: 142 },
  { category: "Service Question", count: 98 },
  { category: "Billing / Invoice", count: 74 },
  { category: "Pest Activity", count: 67 },
  { category: "Rescheduling", count: 55 },
  { category: "New Customer / Sales", count: 41 },
  { category: "Payment", count: 38 },
  { category: "Complaint", count: 22 },
  { category: "Technician Follow-up", count: 18 },
  { category: "Other", count: 79 },
];

export const mockRecentCalls = [
  {
    id: "1",
    callTime: "2026-06-01T14:32:00",
    direction: "inbound",
    fromName: "Steve Johnson",
    fromNumber: "(605) 555-0142",
    agent: "Ashley Terhark",
    durationSeconds: 187,
    primaryCategory: "Billing / Invoice",
    tags: ["invoice confusion", "next service date"],
    shortSummary: "Steve called to ask about his invoice and next service date.",
    processingStatus: "complete",
    sentiment: "neutral",
    followUpRequired: false,
    complaintFlag: false,
    salesOpportunity: false,
  },
  {
    id: "2",
    callTime: "2026-06-01T13:15:00",
    direction: "inbound",
    fromName: "Maria Garcia",
    fromNumber: "(605) 555-0287",
    agent: "Karen Kieffer",
    durationSeconds: 94,
    primaryCategory: "Scheduling",
    tags: ["appointment confirmation"],
    shortSummary: "Maria called to confirm her upcoming service appointment.",
    processingStatus: "complete",
    sentiment: "positive",
    followUpRequired: false,
    complaintFlag: false,
    salesOpportunity: false,
  },
  {
    id: "3",
    callTime: "2026-06-01T12:48:00",
    direction: "inbound",
    fromName: "Unknown",
    fromNumber: "(605) 555-0391",
    agent: "Ashley Terhark",
    durationSeconds: 312,
    primaryCategory: "Complaint",
    tags: ["upset customer", "missed appointment"],
    shortSummary: "Caller upset about a missed technician appointment. Rescheduled and offered discount.",
    processingStatus: "complete",
    sentiment: "negative",
    followUpRequired: true,
    complaintFlag: true,
    salesOpportunity: false,
  },
  {
    id: "4",
    callTime: "2026-06-01T11:22:00",
    direction: "inbound",
    fromName: "Tom Bradley",
    fromNumber: "(605) 555-0519",
    agent: "Jil Traxinger",
    durationSeconds: 156,
    primaryCategory: "New Customer / Sales Opportunity",
    tags: ["new lead", "ant issue", "free quote requested"],
    shortSummary: "Tom called requesting a quote for ant treatment at his new home.",
    processingStatus: "complete",
    sentiment: "positive",
    followUpRequired: true,
    complaintFlag: false,
    salesOpportunity: true,
  },
  {
    id: "5",
    callTime: "2026-06-01T10:05:00",
    direction: "inbound",
    fromName: "Linda Marsh",
    fromNumber: "(605) 555-0674",
    agent: "Karen Kieffer",
    durationSeconds: 78,
    primaryCategory: "Pest Activity",
    tags: ["wasp issue", "callback requested"],
    shortSummary: "Linda reported wasp activity near her deck and requested a technician callback.",
    processingStatus: "complete",
    sentiment: "neutral",
    followUpRequired: true,
    complaintFlag: false,
    salesOpportunity: false,
  },
];
